# Enhanced XGBoost Configuration for Flood Depth Prediction (Tweedie Objective)

# Objective
objective: reg:tweedie                     # models zero + positive skewed values (ideal for flood depth)
tweedie_variance_power: 1.3           # adjust between 1.1–1.9 depending on data
eval_metric: rmse                     # root mean square error

# Boosting rounds & learning
n_estimators: 200                     # total boosting rounds (early stopping will limit this)
learning_rate: 0.5                    # learning rate (try 0.03–0.1 range if tuning)

# Tree structure control using leaf-wise growth
tree_method: hist                     # efficient CPU histogram algorithm (use gpu_hist for GPU)
grow_policy: lossguide                # grow trees leaf-wise (better for imbalanced regression)
max_depth: 0                          # disables depth limit; use max_leaves instead
max_leaves: 128                       # limits number of terminal nodes (controls model complexity)

# Regularization to avoid overfitting
reg_lambda: 10.0                      # stronger L2 regularization
reg_alpha: 1.0                        # stronger L1 regularization
min_child_weight: 10                  # minimum data in a child node before split
gamma: 1.0                            # minimum loss reduction to allow a split
max_delta_step: 1                    # limits size of leaf value updates (adds numerical stability)

# Subsampling
subsample: 0.8                        # row sampling for each tree
colsample_bytree: 0.8                 # feature sampling for each tree

# Optimization and reproducibility
early_stopping_rounds: 30            # stop early if no improvement on validation set
random_state: 42                     # reproducibility
n_jobs: -1                            # utilize all CPU cores
verbosity: 1                          # warnings only (set to 2 for more logs, or 0 for silent)
